apiVersion: v1
kind: Service
metadata:
  name: a1-products
  labels:
    app: a1-products
spec:
  type: NodePort
  selector:
    app: a1-products
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080